version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Building Java application with Gradle..."
      - ./gradlew build


artifacts:
  files: build/libs/*.jar

  discard-paths: yes
